### ISSUE TITLE
Fails to perform check for code size

### ISSUE THREAD

**Issue by propeller3D** [platformio/platform-teensy#106]
I had an issue where inlining a class method made the code too big to fit on the teensy 4. There are checks performed here for code size: https://github.com/PaulStoffregen/teensy_size/blob/main/teensy_size.c#L99

If the code is too big it should return an error and not upload. In my case platformio compiled the program and uploaded, it worked for 2 seconds and then the program crashed and the teensy was unresponsive. Only way to recover it was to press the reset button and re upload working code. If I just build but not upload the ”free for local variables” was showing a negative value.

**Comment by PaulStoffregen** [comment]
For reference, Arduino IDE properly checks the return status from teensy_size.

![screenshot](https://github.com/platformio/platform-teensy/assets/965463/9a1706d1-93b9-46ad-8757-6878c92fab6f)

The build is considered to have failed if teensy_size returns non-zero.  PlatformIO should do the same.

Here is the code shown in the screenshot.

```c++
volatile uint8_t bigbuf[500*1024];

void setup() {
}

void loop() {
  bigbuf[random(sizeof(bigbuf))] = random(256);
}
```
