### ISSUE TITLE
Update gcc version to fix lambda parameter pack expansion bug

### ISSUE THREAD

**Issue by alexozer** [platformio/platform-teensy#12]
I'm experiencing the issue pointed out [here](http://stackoverflow.com/questions/22568642/parameter-packs-not-expanded-with-another-variadic-template-bug-with-gc) and it appears to occur due to a bug in gcc < 4.9. Any chance of updating arm-none-eabi-gcc soon to  fix this?

**Comment by ivankravets** [comment]
Could you try the latest version? `pio update`

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-teensy/releases/tag/v2.4.0
