### ISSUE TITLE
Update framework-arduinoteensy

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#2]
Teensyduino has been updated to 1.29:

https://github.com/PaulStoffregen/cores/tree/1.29

Thanks!

**Comment by valeros** [comment]
Updated only for PlatformIO 3.0. In order to avoid some issues with libraries, I recommend updating to the latest `teensy` platform and PlatformIO from development branches.
```
# uninstall teensy platform
platformio platform uninstall teensy

# uninstall existing PlatformIO
pip uninstall platformio

# install the latest development version
pip install -U https://github.com/platformio/platformio/archive/develop.zip

# install teensy from development branch
platformio platform install https://github.com/platformio/platform-teensy/archive/develop.zip
```

**Comment by valeros** [comment]
Please reopen this issue if you have any problem.

**Comment by profra** [comment]
Teensyduino has been updated to 1.30:

https://github.com/PaulStoffregen/cores/tree/1.30

Please and thanks!

**Comment by ivankravets** [comment]
@profra please open new issue
