### ISSUE TITLE
Update Teensyduino to v1.36

### ISSUE THREAD

**Issue by sstaub** [platformio/platform-teensy#20]
The Pio version (1.7.0) is very confusing because the actual Teensyduino version is in the moment 1.36.
The versions should generally follows the original versions, also on Arduino etcetera.

**Comment by sstaub** [comment]
It seems that framework-arduinoteensy reflect the teensyduino version. If this right you can close this issue and please update to version 1.36

**Comment by slugh23** [comment]
I'll second that.  The new Teensyduino v1.36 was released on 31 March.  Would it be possible please to update it from v1.35 to v1.36.

**Comment by ivankravets** [comment]
@sstaub Teensy development platform consists of multiple frameworks including Arduino/Teensyduino. 

1.7.0 means a version of development platform, where 1.36 is a version of Arduino/Teensyduino framework.
