### ISSUE TITLE
Upload to Teensy via SWD connection

### ISSUE THREAD

**Issue by kwinz** [platformio/platform-teensy#27]
Hi, I would like to upload the build and debug the Teensy via a JTAG or SWD connection and not the Arduino-compatible USB-connection. 

My `platformio.ini` looks like this:
```
[env:teensy36]
platform = teensy
board = teensy36
framework = arduino
upload_protocol = jlink
debug_tool = jlink
```
I have connected the Teensy SWD port to a J-LINK device. Flashing the teensy.hex file built by platformio outside the IDE by the J-FLASH Lite software works without a problem. However when I use upload or debug from within the IDE the  `upload_protocol` is completely ignored and it always tries to use the Teensy Loader, which I don't want.

If I remove `platform`, `board` or `framework` the build fails.

How can I use `upload_protocol jlink` or `upload_protocol = gdb` while still building for Teensy 3.6?

**Comment by ivankravets** [comment]
See example in docs http://docs.platformio.org/en/latest/plus/debugging.html#j-link-as-debugger-and-uploader
