### ISSUE TITLE
Upgrade to teensyduino 1.42

### ISSUE THREAD

**Issue by risq** [platformio/platform-teensy#40]
Hello,

teensyduino 1.42 has been released a few months ago (https://www.pjrc.com/teensyduino-1-42-whats-new/), it would be great to add support into platformio. I could not find where to update it in this repo - the only thing I found was `framework-arduinoteensy` version, which looks like a mirror to the teensyduino software, hosted by platformio ? (I may be wrong)

Thanks.

**Comment by tyler-sommer** [comment]
:+1: I'd like to be able to (not that I actually need to) use all 256K ram on my Teensy 3.5, which was apparently set to 192K due to an erroneous vendor spec!

I noticed that pjrc has not published teensyduino 1.42 on github-- so maybe that's causing some confusion.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-teensy/releases/tag/v3.5.0
