### ISSUE TITLE
Teensyduino has been updated to 1.30

### ISSUE THREAD

**Issue by profra** [platformio/platform-teensy#5]
..... Teensy 3.5/3.6 included (beta):

https://github.com/PaulStoffregen/cores/tree/1.30

Please and thanks!

**Comment by ivankravets** [comment]
What is your OS?

Please test development version:
```
platformio platform uninstall teensy
platformio platform install https://github.com/platformio/platform-teensy.git
```

Does it work with new Teensy?

**Comment by profra** [comment]
@ivankravets I am backer of new Teensy 3.5/3.6 on Kickstarter... Delivery of boards is expected only in October :-( ...I am working on two OS - Linux Mint(CLI) and W10(Atom)... I will let you know as soon as I have the boards.

**Comment by blackketter** [comment]
I can confirm that a simple blink application compiles and uploads just fine to a Teensy 3.6 beta board with the development version.

**Comment by ivankravets** [comment]
@blackketter  thanks for the report! What is your OS?

**Comment by blackketter** [comment]
MacOS X 10.11.6

**Comment by ivankravets** [comment]
Thanks!
