### ISSUE TITLE
USB Mode only shows serial

### ISSUE THREAD

**Issue by devicemodder** [platformio/platform-teensy#52]

**Comment by Theremingenieur** [comment]
This is the actual Teensyduino development state for the Teensy 4.0 by PJRC. Not a PlatformIO issue. Paul Stoffregen said that more USB modes for T4.0 were currently under development and an update published soon.

**Comment by blackketter** [comment]
This issue has been resolved with the latest Teensy release which includes support for additional USB modes.

**Comment by valeros** [comment]
Please update teensy to the latest version. Feel free to reopen if the issue persists.
