### ISSUE TITLE
Update Teensy Loader CLI for Windows

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#54]
Teensyduino has been updated to 1.48 with substantial improvements for Teensy 4.0.  Would be great to pull that in.  Thanks!

**Comment by blackketter** [comment]
Note that the teensy-cli uploader ( https://github.com/PaulStoffregen/teensy_loader_cli )  now works with teensy40 and should be updated as such along with the 1.48 release.

**Comment by ivankravets** [comment]
@PaulStoffregen could you help us with binaries for "teensy_loader_cli" for macOS, Linux (32/64/arm), Windows? 
Thanks!

**Comment by ivankravets** [comment]
1. Teensyduino 1.48 is out, see https://community.platformio.org/t/teensy-dev-platform-4-6-0/10514

2. I updated this issue to "Update Teensy Loader CLI". So, let's wait when someone prepares binaries for `teensy_loader_cli` for macOS, Linux, Windows.

**Comment by vshymanskyy** [comment]
PIO `teensy-cli` tool cannot upload to `Teensy 4.0` due to this.

**Comment by ivankravets** [comment]
`teensy_loader_cli` has been updated for macOS and Linux x64. Now, the only Window CLI is outdated.

**Comment by ivankravets** [comment]
`teensy_loader_cli` was also updated for Windows. 

Thanks, @valeros, @vshymanskyy for the binaries!

**Comment by PaulStoffregen** [comment]
@ivankravets - Soon Teensy 4.0 will begin uses a -DARDUINO_TEENSY40 define, similar to the convention Arduino uses for their boards.  Details here:

https://forum.pjrc.com/threads/58028?p=227510&viewfull=1#post227510

Recommend you add this to the flags used for Teensy compile, in prep for the next core lib update.

**Comment by ivankravets** [comment]
@PaulStoffregen thanks for the info! Should we also add it to other boards? For example, `-D ARDUINO_TEENSY30`? 

@valeros please add for all Teensy boards `-D ARDUINO_***` macro, we have it for other dev-platforms (ESP32, ESP8266, AVR, Atmel SAM, etc)

**Comment by PaulStoffregen** [comment]
> Should we also add it to other boards?

Yes, though it probably will only matter with Teensy 4.x.

Probably a good idea for non-Teensy boards.  But important to check their boards.txt file, so you get the exact same "build.board" string each board defines for use in Arduino.
