### ISSUE TITLE
Update to Teensy 1.49

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#56]
Teensyduino has been updated to 1.49

https://github.com/PaulStoffregen/cores/releases/tag/1.49

https://forum.pjrc.com/threads/59054-Teensyduino-1-49-Released

**Comment by rcappuccio** [comment]
Please update to Teensy 1.49

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-teensy/releases/tag/v4.7.0
