### ISSUE TITLE
Update to Teensy 1.51

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#58]
See https://github.com/PaulStoffregen/cores/releases/tag/1.50

Thanks!

**Comment by blackketter** [comment]
Whoops, 1.51 is out now:  https://github.com/PaulStoffregen/cores/releases/1.51

**Comment by Theremingenieur** [comment]
It's a little unsatisfying... The latest Teensyduino releases are huge steps forward and fix lots of issues, especially around the Teensy 4. When 1.49 came out on Jan 14th, we got the PlatformIO update 9 days later. 1.50 came out on Feb 1st, and we haven't seen an update for 32 days and still pending. 1.51 came out on Feb 22nd, 10 days ago. PJRC is already working on the 1.52 beta for 8 days now. I don't know who is being PlatformIO, but I'd suggest that they read the PJRC forum from time to time, follow the beta publications and be prepared at the release date.

**Comment by blackketter** [comment]
Any idea when this might happen, @valeros & @ivankravets ?

**Comment by ivankravets** [comment]
You can subscribe for releases here https://github.com/PaulStoffregen/cores/releases

We will fix this issue soon.

**Comment by Theremingenieur** [comment]
Thank you for the quick reply! Much appreciated!

**Comment by valeros** [comment]
Packages have been updated, please retest with the upstream version http://docs.platformio.org/en/latest/platforms/teensy.html#upstream

**Comment by blackketter** [comment]
Initial testing seems ok.  Thanks!

**Comment by Theremingenieur** [comment]
Update worked. Thank you!
