### ISSUE TITLE
Math libs removed from arduino.py

### ISSUE THREAD

**Issue by wcalvert** [platformio/platform-teensy#59]
In the file .platformio/platforms/teensy/builder/frameworks/arduino.py, lines 264 - 276, the logic has been commented out to include the math libs in the environment variables. This has the effect that code which needs arm_math.h for example, cannot be compiled.

I'm not sure if this was intentional or not because it was not commented out in earlier platform versions.

**Comment by valeros** [comment]
Thanks, fixed! Please retest with the upstream version http://docs.platformio.org/en/latest/platforms/teensy.html#upstream
