### ISSUE TITLE
Update teensy_loader_cli

### ISSUE THREAD

**Issue by tainnok** [platformio/platform-teensy#60]
Version of teensy_loader_cli which is part of platformIO is outdated and does NOT support teensy4.
Please update platformIO-internal version of teensy_loader_cli to the actual source of official repo: https://github.com/PaulStoffregen/teensy_loader_cli

see also my post in platformIO-Community:
https://community.platformio.org/t/how-to-remote-upload-to-teensy4

But actual Version of teensy_loader_cli does not handle the soft-boot correct.
Workaround: Add the following to the (acutal empty) packages/tool-teensy/teensy_reboot

> SERIAL_TEENSY_DEVICE=`find /dev/serial/by-id/ -name "usb-Teensyduino*"`;
> echo "-> Performing soft resset (baud = 134 hack). $SERIAL_TEENSY_DEVICE";
> lsusb | grep Teensy;
> stty -F $SERIAL_TEENSY_DEVICE 9600
> sleep 1;
> stty -F $SERIAL_TEENSY_DEVICE 134
> sleep 1;
> lsusb | grep Teensy;
> echo "-> Should be ready to program...";

This will fix the problem.
See also this post on the teensy-forum:
https://forum.pjrc.com/threads/57176-teensy_loader_cli-and-Teensy-4-0?p=220204&viewfull=1#post220204

With this two changes it's possible to use the platformIO-Remote feature also with the teensy4.

**Comment by valeros** [comment]
Thanks, we've updated `teensy_loader_cli` tool for Linux, please retest with the upstream version http://docs.platformio.org/en/latest/platforms/teensy.html#upstream
