### ISSUE TITLE
Add support for double and triple USB serial

### ISSUE THREAD

**Issue by romi2002** [platformio/platform-teensy#65]
Whenever the build_flag `-DUSB_DUAL_SERIAL` is set, the code fails to compile as `-DUSB_SERIAL` is added by default. For now, a workaround is adding `-UUSB_SERIAL` to the `build_flag` in order to be able to compile with double serial support.

**Comment by valeros** [comment]
Thanks, fixed! For now, please use `build_unflags` instead of `-UUSB_SERIAL` https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-unflags
