### ISSUE TITLE
teensy36 should use teensy_loader_cli and not Teensy.app for uploading

### ISSUE THREAD

**Issue by blackketter** [platformio/platform-teensy#7]
teensy31 uploads using the teensy_loader_cli binary, but teensy36 uses Teensy.app on MacOS
For consistency both should use teensy_loader_cli, like Linux.

MacOS: Sierra & El Capitan
PlatformIO: 3.0.1
framework-arduinoteensy: 1.130

I'd love to help fix this but I'm at a loss to see where this is specified.

**Comment by ivankravets** [comment]
I opened an issue for that 18 days ago https://github.com/PaulStoffregen/teensy_loader_cli/issues/28

It looks that @PaulStoffregen doesn't have time for Teensy CLI

**Comment by PaulStoffregen** [comment]
While working on Kickstarter, I don't have time for anything else.

Ping me next week....

**Comment by ivankravets** [comment]
Thanks, @PaulStoffregen! We will wait!

**Comment by ivankravets** [comment]
@PaulStoffregen could you take a look at Teensy CLI? Thanks!

**Comment by ivankravets** [comment]
@PaulStoffregen do you have any news?

**Comment by PaulStoffregen** [comment]
I've updated teensy_loader_cli.  You can now use it for all Teensy boards, on Windows, Linux and Mac.

Windows and Mac binaries are now available on the main page.

http://www.pjrc.com/teensy/loader_cli.html
