### ISSUE TITLE
Please update this platform as Teensyduino 1.54 has just been released

### ISSUE THREAD

**Issue by sbfreddie** [platformio/platform-teensy#74]
Please update to Teensy 1.54, it has been released.

**Comment by jakespeed1311** [comment]
Hi yes please suppport !
Tx Jake

**Comment by daveboulden** [comment]
Adding my voice too. Please update to 1.54 when possible if not already underway.

**Comment by valeros** [comment]
Hi guys, Teensyduino has been updated to the latest v1.54. Please retest your projects with the upstream version of the platform:
```ini
[env:teensy31]
platform = https://github.com/platformio/platform-teensy.git
framework = arduino
board = teensy31
```

**Comment by CorBer** [comment]
Hi,

I just tested this for a Teensy41 but it does not "pick" up. I am in VisualCode and this is my platformio.ini

[env:teensy41]
platform = https://github.com/platformio/platform-teensy.git
board = teensy41
framework = arduino
build_flags = -Wl,--print-memory-usage

regards
Cor

**Comment by valeros** [comment]
Hi @CorBer ! Could you please provide a bit more info? What exactly is not picked up?

**Comment by CorBer** [comment]
Well it simply kept using the 1.153 version. But MaxGerhardt helped me out. I used
pio platform update teensy and now I see 1.154 !! Thanks

**Comment by valeros** [comment]
@CorBer Please attach here your build log.

**Comment by maxgerhardt** [comment]
> platform = teensy

You must use bleeding edge platform per above there.

```ini
platform = https://github.com/platformio/platform-teensy.git
```

**Comment by CorBer** [comment]
Hi Max,
Sorry for the cross-posts but its important on 2 locations :)
https://community.platformio.org/t/teensyduino-1-54-beta-7/19824/21

I have followed the suggests by Max (remove the framework/packages/cache dirs) and then did a recompile with the "bleeding edge" platform. Now works as planned and compiles my code as expected.

Thanks to both Max and valeros.
