### ISSUE TITLE
Teensy 1.55 was released

### ISSUE THREAD

**Issue by ssilverman** [platformio/platform-teensy#79]
Hello kindred folks. Teensy 1.55 was released. I just noticed that there's no git tag for "1.55" in the Teensy `cores` repo, however. I'm surmising this is the reason it wasn't picked up.

I'm fairly certain that https://github.com/PaulStoffregen/cores/commit/f452eb4f1608d725acfcc4fa80ad6c440fe54110 is the latest commit for that version because 1.55 was announced on Sep 15 and the next changes are on Sep 20.

**Comment by valeros** [comment]
Have you tried to run `pio platform update teensy` in your terminal?
