### ISSUE TITLE
Please update, Teensyduino 1.56 has been released

### ISSUE THREAD

**Issue by skunktrading** [platformio/platform-teensy#84]
Teensyduino 1.56 has been released

**Comment by PaulStoffregen** [comment]
This time I remembered to tag a release on Github.  Hope that helps?

https://github.com/PaulStoffregen/cores/releases/tag/1.56

**Comment by PaulStoffregen** [comment]
Please also make sure PlatformIO users with Teensy get this copy of FastLED when using Teensy.

https://github.com/PaulStoffregen/FastLED

2 important fixes for Teensy users haven't been merged to upstream FastLED yet.  We've had several reports of these FastLED bugs on the forum, including some reports from PlatformIO users.

**Comment by valeros** [comment]
HI @skunktrading ! The Teensyduino package has been updated to the latest 1.56. You can try it out using the upstream version of the platform:
```
[env:teensy40]
platform = https://github.com/platformio/platform-teensy.git
framework = arduino
board = teensy40 
```
A new stable release of the `teensy` platform is planned to published next month.
