### ISSUE TITLE
Correct Teensy Loader Version? 

### ISSUE THREAD

**Issue by m-r-m-s** [platformio/platform-teensy#86]
Is the version of the Teensy Loader I am using correct? It shows 1.55 even though I am on Teensy 1.56? 
EDIT: This is a bit confusing because the Teensy versions are different but it appears that this version is correct: 
https://registry.platformio.org/tools/platformio/tool-teensy/versions

Here's the output from platformio run --target upload:

`Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensylc.html
PLATFORM: Teensy (4.15.0) > Teensy LC
HARDWARE: MKL26Z64 48MHz, 8KB RAM, 62KB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES:
 - **framework-arduinoteensy 1.156.0 (1.56)**
 - **tool-teensy 1.155.0 (1.55)**
 - toolchain-gccarmnoneeabi 1.50401.190816 (5.4.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 93 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <TeensyEncoderTool> 2.2.0
|   |-- <Bounce2> 2.55
|-- <MIDI Library> 5.0.2
Building in release mode
Linking .pio/build/teensylc/firmware.elf
Checking size .pio/build/teensylc/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [===       ]  30.9% (used 2532 bytes from 8192 bytes)
Flash: [==        ]  24.4% (used 15460 bytes from 63488 bytes)
Building .pio/build/teensylc/firmware.hex
Configuring upload protocol...
AVAILABLE: jlink, teensy-cli, teensy-gui
CURRENT: upload_protocol = teensy-gui`

**Comment by valeros** [comment]
Hi @m-r-m-s ! The `tool-teensy` package has been updated to the latest 1.57.
