### ISSUE TITLE
Build warning using TD1.57

### ISSUE THREAD

**Issue by skunktrading** [platformio/platform-teensy#90]
Hi. Since upgrading (Thanks very much btw) I get the following warnings during LDF when building:
`Library Manager: Could not parse manifest -> Expecting ',' delimiter: line 4 column 3 (char 46)
Warning! Ignoring broken library manifest in /home/skunk/.platformio/packages/framework-arduinoteensy/libraries/FreqCount
`
Seems there is a missing comma on the "version" line in file /libraries/FreqCount/library.json

Other than that my project builds and runs just fine with 1.57

**Comment by david-res** [comment]
I have the same warning.
Added the missing comma and it fixed the issue

**Comment by skunktrading** [comment]
Thanks for confirming. I'm not sure whether this is Paul's bug or if that that file is generated by some pio scripting.

**Comment by PaulStoffregen** [comment]
Fixed https://github.com/PaulStoffregen/FreqCount/commit/8e993136939a15542611c790e2b76eb9bb6d165a

**Comment by valeros** [comment]
Thanks for reporting, please run `pio platform update teensy` in the IDE terminal to get the latest package with the bugfix.
