### ISSUE TITLE
Compiler error with c++ templates using teensy platform only

### ISSUE THREAD

**Issue by ktgilliam** [platformio/platform-teensy#94]
I can compile this code using gcc or the native platform in platformio, but I am getting an error when I build for the Teensy4.1:

```
template <typename T>
inline T saturate(T val, T lower, T upper)
{
   T val1 = val > lower ? val : lower;
   T val2 = val1 < upper ? val1 : upper;
   return val2;
}

int main()
{
    double v = 1.234;
    saturate(v, 0.0, 90.0);
    return 0;
}
```

The error I get is:
`src/exec/MainExec.cpp: In function 'int main()':
src/exec/MainExec.cpp:12:26: error: no matching function for call to 'saturate(double&, float, float)'
     saturate(v, 0.0, 90.0);`

Expected behavior: the compiler to make all three arguments doubles. 

Is this a bug with the teensy platform or with the compiler?

**Comment by PaulStoffregen** [comment]
I tried with Arduino IDE and it seems to work.

![image](https://user-images.githubusercontent.com/965463/196658234-2bdc74f6-4276-4f11-9176-ae7421ab8dae.png)

**Comment by PaulStoffregen** [comment]
However, it does fail if I use Teensy 3.2, where code is compiled with "-fsingle-precision-constant" option.  This is the expected result with -fsingle-precision-constant.

Perhaps PlatformIO is incorrectly using -fsingle-precision-constant with Teensy 4.1?  It is only supposed to be used with the older boards.

**Comment by blackketter** [comment]
Yup, it seems that -fsingle-precision-constant is used with all boards on platformio.  I'll file a bug.
